### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by akbir** [y0ast/VAE-Torch#18]
Hey I'm downloaded your encoder to use. 

Trying to run it, the load.lua function tries to "require" pl.data which you don't explicitly ask for, I traced the problem to function 'loadBinarizedMNIS'(lines 40-55).

 I think you got confused between dataset and data when defining new variables. Maybe you can check if thats okay?

Sorry in advance if this confusing.

**Comment by y0ast** [comment]
I believe penlight is a requirement of the torch7 file reading tools. I didn't mention it as a requirement since it is installed with torch7 itself: https://github.com/torch/ezinstall/blob/c33da5962a1398428d5c068c0f227e57d609399d/install-luajit%2Btorch#L61

The code looks ok to me. Please try again with an official install of torch7 and let me know if you have any issues. Closing for now.
